import React from 'react';
import {View, Text, StyleSheet} from 'react-native';

export default function HomeScreen() {
    return (
        <View style={styles.HomeStyle}>
            <Text>
                firt
            </Text>
            <Text>
            fdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfdsfds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
            <Text>
                fds
            </Text>
        </View>
    )
}

const styles = StyleSheet.create({
    HomeStyle: {
        marginLeft: 20,
        marginRight: 20,
        paddingTop: 20
    }
});